config/routes.rb
Rails.application.routes.draw do
   root 'home#index'
   resources :employees
   resources :documents


   #Custom Routes
  get 'about' => 'pages#about_us'
  get 'contact' => 'pages#contact_us'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-and-condition' => 'pages#terms_and_condition'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord

  DOC_TYPES = ['Marksheet','Personal id','Address proof','Pancard','Addhar cars','Other'].freeze

  belongs_to :employee
  has_one_attached :image
  validates :name, :doc_type, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord

  has_many :documents

  validates :first_name, :last_name, presence:true
  validates :personal_email, presence:true, uniqueness:true
  validates :city ,:state, :country,:pincode,:address_line_1,presence:true
  validates :date_of_brith, :date_of_joining, :job_title,presence:true
  
  def name
    "#{first_name} #{last_name}".strip
  end

  def address
    "#{address_line_1} #{city} #{state} #{country} #{pincode}".strip
  end 

  def name_with_id
    "#{first_name} #{last_name}  
    #{personal_email}".strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/documents_controller.rb
class DocumentsController <ApplicationController
  before_action :set_document,only:[:edit, :update, :show, :destroy]

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to documents_path, notice: 'Document has been created succesfully'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to documents_path, notice: 'Document has been Upadate successfuly'
    else
      render :edit 
    end
  end

  def show
  end

  def destroy

    if @document.destroy
      redirect_to documents_path, notice: 'Employee has been delete successfuly'
    end
  end

  private
  def document_params
    params.require(:document).permit(:name, :doc_type, :employee_id, :image)
  end
  def set_document
    @document = Document.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to documents_path,notice:error
  end
end

app/controllers/employees__controller.rb
class EmployeesController <ApplicationController
  before_action :set_employee,only:[:edit, :update, :show, :destroy]
  def index
      @employees = Employee.all
    end
    def new
      @employee = Employee.new
    end
    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        redirect_to employees_path, notice:'Employee has been create successfuly'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @employee.update(employee_params)
       redirect_to employees_path, notice:'Employee has been  Upadate successfuly'
     else
      render :edit
    end
  end

  def show 
  end
  def destroy

    if @employee.destroy
      redirect_to employees_path, notice:'Employee has been Delete successfuly'
  end
end 


private

def employee_params
  params.require(:employee).permit(:first_name,  :last_name, :personal_email, :state, :city, :country, :pincode, :address_line_1 )
end
def set_employee
  @employee = Employee.find(params[:id])
 rescue ActiveRecord::RecordNotFound => error
  redirect_to employees_path, notice:error

 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title_text = 'Hello World'
    @subtitle_text = 'I am learning Rails!'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_condition
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_form.html.erb
<%= form_with  model:document do |form| %>
<div class="form">
  <div class="row mt-2">
    <div class="col-lg-4">
      <div class="form-group">
        <%= form.label :name,class:'mb-2'%>
        <%=form.text_field :name,class:'form-control form-control-lg rounded-0'%>
        <% @document.errors.full_messages_for(:name).each do |message| %>
        <p class=" text-danger"><%= message %></p>
        <% end %>
      </div>



      <div class="form-group mt-2">

        <%= form.label :doc_type,class:'mb-2'%>
        <%= form.select :doc_type, options_for_select(Document::DOC_TYPES, selected:document.doc_type), {prompt: 'Select document type'},{class:'form-select form-select-lg rounded-0'} %>
        
        <% @document.errors.full_messages_for(:doc_type).each do |message| %>
        <p class=" text-danger"><%= message %></p>
        <% end %>
      </div>


      <div class="form-group mb-3">
        <%= form.label :employee_id,class:'mb-2'%>
        <%= form.select :employee_id, options_for_select(Employee.all.map {|employee| [employee.name_with_id, employee.id]}, selected:document.doc_type), {prompt: 'Select employee'},{class:'form-select form-select-lg rounded-0'} %>

        <% @document.errors.full_messages_for(:employee_id).each do |message| %>
        <p class=" text-danger"><%= message %></p>
        <% end %>
      </div>

      <div class="form-group">
        <div class="row">
          <%= form.label :image, class: 'mb-2' %>
          <%= form.file_field :image %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 mt-2  ">
          <%= form.submit class:'btn btn-primary  rounded-0'%>
          <%= link_to "Back to Employees list", documents_path,class:'btn btn-outline-danger  rounded-0'%>
        </div>
      </div>
    </div>
  </div>
  <%end%>

app/views/documents/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Create Edit Document</h2>
    </div>
  </div>
  <%= render 'form', document: @document %>
</div>

app/views/documents/index.html.erb
<div class="col-lg-12">
  <%= flash[:notice] %>
  <div class="card mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Document Table</h2>
    </div>
  </div>
   <%= link_to "Create New Document", new_document_path, class:"btn btn-primary btn-md mb-4 rounded-0" %>
  <table class="table table-bordered">
    <thead>
      <tr>
         <th> Name</th>
        <th>Doc type</th>
        <th>Employee id</th>
        <th>Action</th>
      </tr>
    </thead>
    <tboby>
      <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.doc_type %></td>
        <td><%= link_to document.employee.name, employees_path(document.employee) %></td>
        <td>
          <%= link_to "Edit",edit_document_path(document), class:"btn btn-outline-primary "  %>
           <%= link_to "View",document_path(document), class:"btn btn-outline-info"  %>
             <%= link_to "Delete",document_path(document), class:"btn btn-outline-danger",method: :delete, data: { confirm: 'Are you sure to delete this document?'} %>
           </td>

      </tr>
      <% end %>
    </tboby>
  </table>

app/views/documents/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Create New Document</h2>
    </div>
  </div>
  <%= render 'form', document: @document %>
</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body mx-5 text-center">
      <h2 class="text-center border w-50 mx-auto ">Doc  Details</h2>
      <div class="row ">
        <div class="col-lg-6 mt-3 text-center mx-auto">
          <% if @document.image.attached? %>
          <%= image_tag @document.image, class: "img-fluid" %>
          <%end%>
          <p class="lead"><strong> Name:</strong> <%= @document.name %></p>
          <p class="lead"><strong> Type</strong> <%= @document.doc_type %></p>
          <p class="lead"><strong>Employee:</strong> <%= @document.employee.name %></p>
          
        </div>
      </div>

      <%= link_to 'Back to Documents list',documents_path,class:"btn btn-outline-secondary text-dark rounded-0 mx-auto "%>
      <%= link_to 'Edit  Document Details ',edit_document_path(@document),class:"btn btn-outline-primary mx-auto" %>

    </div>
  </div>
</div>

app/views/employees/_form.html.erb
<%= form_with model:employee do |form| %>
  <div class="row">
    <div class="col-lg-4">
     <div class="form-group">
        <%= form.label :first_name,class:'mb-2'%>
        <%=form.text_field :first_name,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:first_name).each do |message| %>
       <p class=" text-danger"><%= message %></p>
       <% end %>
     </div>
   </div>

   
    <div class="col-lg-4">
     <div class="form-group">
        <%= form.label :last_name,class:'mb-2'%>
        <%=form.text_field :last_name,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:last_name).each do|message| %>
        <p class="text-danger"><%= message %></p>
         <% end %>
     </div>
   </div>

    <div class="col-lg-6 mt-3">
     <div class="form-group">
       <%= form.label :personal_email,class:'mb-2'%>
       <%= form.text_field :personal_email,class:'form-control form-control-lg rounded-0',placeholder:'xyz@gmail.com'%>
        <% @employee.errors.full_messages_for(:personal_email).each do|message| %>
        <p class="text-danger"><%= message %></p>
          <% end %>
     </div>
   </div>

    <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :about,class:'mb-2'%>
       <%=form.text_field :about,class:'form-control form-control-lg rounded-0',row:'5' %>
        <% @employee.errors.full_messages_for(:about).each do|message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
     </div>
    </div>
     <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :date_of_brith,class:'mb-2'%>
       <%=form.date_field :date_of_brith,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:date_of_brith).each do|message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
     </div>
    </div>
     <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :job_title,class:'mb-2'%>
       <%=form.text_field :job_title,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:job_title).each do|message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
     </div>
    </div>



     <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :date_of_joining,class:'mb-2'%>
       <%=form.date_field :date_of_joining,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:date_of_joining).each do|message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
     </div>
    </div>
      
   <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :city,class:'mb-2'%>
        <%=form.text_field :city,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:city).each do|message| %>
       <p class="text-danger"><%= message %></p>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :state,class:'mb-2'%>
       <%=form.text_field :state,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:state).each do|message| %>
        <p class="text-danger"><%= message %></p>
        <% end %>
     </div>
    </div>
    <div class="col-lg-4 mt-3">
      <div class="form-group">
       <%= form.label :country,class:'mb-2'%>
       <%=form.text_field :country,class:'form-control form-control-lg rounded-0'%>
       <% @employee.errors.full_messages_for(:country).each do|message| %>
       <p class="text-danger"><%= message %></p>
        <% end %>
     </div>
   </div>
   <div class="col-lg-4 mt-3">
     <div class="form-group">
       <%= form.label :pincode,class:'mb-2'%>
       <%=form.text_field :pincode,class:'form-control form-control-lg rounded-0'%>
        <% @employee.errors.full_messages_for(:pincode).each do|message| %>
       <p class="text-danger"><%= message %></p>
        <% end %>
        </div>
      </div>
      <div class="col-lg-4 mt-3">
        <div class="form-group">
          <%= form.label :address_line_1,class:'mb-2'%>
          <%=form.text_field :address_line_1,class:'form-control form-control-lg rounded-0'%>
          <% @employee.errors.full_messages_for(:address_line_1).each do|message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
     

        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 mt-2  ">
      <%= form.submit class:'btn btn-primary  rounded-0'%>
      <%= link_to "Back to Employees list", employees_path,class:'btn btn-outline-danger  rounded-0'%>
  <% end %>

app/views/employees/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Edit Employee Information</h2>
    </div>
  </div>

  <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
  <%= flash[:notice] %>
  <div class="card mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Employee Table</h2>
    </div>
  </div>


  <div class="col-lg-12 d-flex justify-content-between mb-2">
    <%= link_to "Create New Employee", new_employee_path, class:"btn btn-primary btn-md rounded-0" %>
    <div class="dropdown ">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
       View Type
     </button>
     <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li> <%= link_to "Table",employees_path(view_type: 'table'), class:"primary  dropdown-item"  %></li>
      <li> <%= link_to "Accordion",employees_path(view_type: 'accordian'), class:"info dropdown-item"  %></li>

    </ul>
  </div>
</div>
</div>

<%  if params[:view_type].present? && params[:view_type] == 'table' %>

<table class="table table-bordered">
  <thead>
    <tr>
     <th> Name</th>
     <th>Email</th>
     <th>Address</th>
     <th>Action</th>
   </tr>
 </thead>
 <tboby>
  <% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.personal_email %></td>
    <td><%= employee.address %></td>
    <td>
      <%= link_to "Edit",edit_employee_path(employee), class:"btn btn-outline-primary"  %>
      <%= link_to "View",employee_path(employee), class:"btn btn-outline-info"  %>
      <%= link_to "Delete",employee_path(employee), class:"btn btn-outline-danger",method: :delete, data: { confirm: 'Are you sure to delete this employee?'} %>
    </td>

  </tr>
  <% end %>
</tboby>
</table>
<% end %>

<% if params[:view_type] !='table' %>
<div class="accordion" id="accordionExample">
  <% @employees.each_with_index do |employee, index| %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading_<%= index + 1 %>">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= index + 1 %>" aria-expanded="true" aria-controls="collapse_<%= index + 1 %>">
       <%= employee.name_with_id %>
     </button>
   </h2>
   <div id="collapse_<%= index + 1 %>" class="accordion-collapse collapse " aria-labelledby="heading_<%= index + 1 %>" data-bs-parent="#accordionExample">
    <div class="accordion-body">
      <h2 class="text-center border w-50 mx-auto ">Employee Details</h2>
      <div class="row ">
        <div class="col-lg-6 mt-3">
          <h3>Personal Information</h3>
          <p class="lead"><strong>First Name:</strong> <%= employee.first_name %></p>

          <p class="lead"><strong>Last Name:</strong> <%= employee.last_name %></p>
          <p class="lead"><strong> Email:</strong> <%= employee.personal_email %></p>
        </div>
        <div class="col-lg-6 mt-3">
          <h3>Address Information</h3>
          <p class="lead"><strong>Address:</strong> <%= employee.address_line_1 %></p>

          <p class="lead"><strong>City:</strong> <%= employee.city %></p>
          <p class="lead"><strong> State:</strong> <%= employee.state %></p>
          <p class="lead"><strong> Pincode:</strong> <%= employee.pincode %></p>
        </div>
        <div class="col-lg-12">
          <%= link_to "Edit",edit_employee_path(employee), class:"btn btn-outline-primary"  %>
          <%= link_to "View",employee_path(employee), class:"btn btn-outline-info"  %>
          <%= link_to "Delete",employee_path(employee), class:"btn btn-outline-danger",method: :delete, data: { confirm: 'Are you sure to delete this employee?'} %>


        </div>
      </div>
    </div>

  </div>
</div>
<% end %>
<% end %>

</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Create New Employee</h2>
    </div>
  </div>

  <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body mx-5">
      <h2 class="text-center border w-50 mx-auto ">Employee Details</h2>
      <div class="row ">
        <div class="col-lg-6 mt-3">
          <h3>Personal Information</h3>
          <p class="lead"><strong>First Name:</strong> <%= @employee.first_name %></p>
          
          <p class="lead"><strong>Last Name:</strong> <%=@employee.last_name %></p>
          <p class="lead"><strong> Email:</strong> <%=@employee.personal_email %></p>
        </div>
        <div class="col-lg-6 mt-3">
          <h3>Address Information</h3>
          <p class="lead"><strong>Address:</strong> <%= @employee.address_line_1 %></p>
         ss
          <p class="lead"><strong>City:</strong> <%=@employee.city %></p>
          <p class="lead"><strong> State:</strong> <%=@employee.state %></p>
          <p class="lead"><strong> Pincode:</strong> <%=@employee.pincode %></p>
          <p class="lead"><strong>date_of_brith</strong> <%=@employee.date_of_brith %></p>
          <p class="lead"><strong>job_title</strong> <%=@employee.job_title %></p>
          <p class="lead"><strong>date_of_joining</strong> <%=@employee.date_of_joining %></p>
        </div>
      </div>


      <% if @employee.documents.present? %>
        <div class="row mt-5 mb-3">
          <h2 class="text-center">Employee Document</h2>
          <%  @employee.documents.each do |document| %>
            <div class="card  ">
              <div class="card-body body-control">
                <div class="row">
                  <% if document.image.attached? %>
                  <div class="col-lg-4 mx-auto mb-2">
                    <%= image_tag document.image ,class:"img-fluid  mt-5" %>
                  </div>
                  <% end %>
                  <div class="col-lg-4 mb-2">
                    <p class="lead"><%= document.name %></p>
                  </div>
                  <div class="col-lg-4 mt-2">
                    <p class="lead"> <%= document.doc_type %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <%= link_to 'Back to Employees list',employees_path,class:"btn btn-outline-secondary text-dark rounded-0 w-5 mt-3 " %>  
      <%= link_to'Edit  Employee Details ',edit_employee_path(@employee),class:"btn btn-outline-primary mt-3 " %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1><%= @title_text %></h1>
<p><%= @subtitle_text %></p>

<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'shared/header' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
   </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-5">About Us Hr-Mitra</h1>
  <%= render 'shared/bummy_content' %>
</div>
<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<div class="col-lg-12">
  <h1 class="text-center mt-5 mb-5">Contact HR-Mitra</h1>
  <%= render 'shared/bummy_content' %>
</div>
<%= render 'shared/links' %>

app/views/pages/privacy_policy.html.erb
<h1>Pages#privacy_policy</h1>
<p>Find me in app/views/pages/privacy_policy.html.erb</p>
<%= render 'shared/links' %>

app/views/pages/terms_and_condition.html.erb
<h1>Pages#terms_and_condition</h1>
<p>Find me in app/views/pages/terms_and_condition.html.erb</p>
<%= render 'shared/links' %>

app/views/shared/_bummy_content.html.erb
<p class="lead">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
<p class="lead">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
<p class="lead">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hr Mitra</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<%= link_to 'About-us', about_path, target: '_blank', style: 'color:red;'  %>
<%= link_to 'Contact-us', contact_path, target: '_blank', style: 'color:red;' %>
<%= link_to 'Privacy-policy', privacy_policy_path, target:'_blank', style: 'color:red;' %>
<%= link_to 'Terms and Codition', terms_and_condition_path, target:'_blank', style: 'color:red;' %>